// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1CChOCO6f4tDxvMuZ4aHxROdbrJtrkk',
    appId: '1:230137955722:web:a4e4d8a2d3f6e94e347473',
    messagingSenderId: '230137955722',
    projectId: 'agreement-81f5e',
    authDomain: 'agreement-81f5e.firebaseapp.com',
    storageBucket: 'agreement-81f5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtcxBIQGuVk5M-K_bE3eVA0vT5pUNHA48',
    appId: '1:230137955722:android:a1ec264238e7df57347473',
    messagingSenderId: '230137955722',
    projectId: 'agreement-81f5e',
    storageBucket: 'agreement-81f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ibv-P_dFUDtEj0gvyH4ZkUyeu2HSea0',
    appId: '1:230137955722:ios:7222c257a191c5c0347473',
    messagingSenderId: '230137955722',
    projectId: 'agreement-81f5e',
    storageBucket: 'agreement-81f5e.firebasestorage.app',
    iosBundleId: 'com.example.agreementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ibv-P_dFUDtEj0gvyH4ZkUyeu2HSea0',
    appId: '1:230137955722:ios:7222c257a191c5c0347473',
    messagingSenderId: '230137955722',
    projectId: 'agreement-81f5e',
    storageBucket: 'agreement-81f5e.firebasestorage.app',
    iosBundleId: 'com.example.agreementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1CChOCO6f4tDxvMuZ4aHxROdbrJtrkk',
    appId: '1:230137955722:web:ee26042c01b9dd4c347473',
    messagingSenderId: '230137955722',
    projectId: 'agreement-81f5e',
    authDomain: 'agreement-81f5e.firebaseapp.com',
    storageBucket: 'agreement-81f5e.firebasestorage.app',
  );
}
